#! /usr/bin/python3 -i

import logging
import icat
import icat.config
from icat.query import Query

logging.basicConfig(level=logging.INFO)
#logging.getLogger('suds.client').setLevel(logging.DEBUG)

config = icat.config.Config(ids="optional")
client, conf = config.getconfig()
sessionId = client.login(conf.auth, conf.credentials)

print("Login to", conf.url, "was successful.")
username = client.getUserName()
print("User:", username)

# Local Variables:
# mode: python
# End:
